# depth dose ------------------------------------------------------------------
/gate/actor/addActor                            DoseActor  depthdose
/gate/actor/depthdose/save                      output/depth-dose.txt
/gate/actor/depthdose/attachTo    	         phantom
/gate/actor/depthdose/stepHitType               random
/gate/actor/depthdose/setPosition               0 0 0 cm
/gate/actor/depthdose/setResolution             1 100 1
/gate/actor/depthdose/setVoxelSize              5 3 5 mm
/gate/actor/depthdose/saveEveryNSeconds         60
/gate/actor/depthdose/enableEdep                true
/gate/actor/depthdose/enableUncertaintyEdep     true
/gate/actor/depthdose/enableDose                false
/gate/actor/depthdose/enableUncertaintyDose     false
/gate/actor/depthdose/enableNumberOfHits        false

# dose profiles ---------------------------------------------------------------
/gate/actor/addActor                            DoseActor  doseprofile
/gate/actor/doseprofile/save                    output/dose-profile.txt
/gate/actor/doseprofile/attachTo                phantom
/gate/actor/doseprofile/stepHitType             random
/gate/actor/doseprofile/setPosition             0 50 0 mm
/gate/actor/doseprofile/setResolution           100 1 1
/gate/actor/doseprofile/setSize                 300 5 5 mm
/gate/actor/doseprofile/saveEveryNSeconds       60
/gate/actor/doseprofile/enableEdep              true
/gate/actor/doseprofile/enableUncertaintyEdep   true
/gate/actor/doseprofile/enableDose              false
/gate/actor/doseprofile/enableUncertaintyDose   false
/gate/actor/doseprofile/enableNumberOfHits      false

# statistic -------------------------------------------------------------------
/gate/actor/addActor                            SimulationStatisticActor stat
/gate/actor/stat/save                           output/qa-static.txt
/gate/actor/stat/saveEveryNSeconds              60
