/gate/source/addSource                  MyBeam phaseSpace
/gate/source/MyBeam/addPhaseSpaceFile   psf/gaga/6FFF.pt
/gate/source/MyBeam/setParticleType     gamma
/gate/source/MyBeam/setPytorchParams    psf/gaga/6FFF.json
/gate/source/MyBeam/setPytorchBatchSize 1000
/gate/source/MyBeam/attachTo            gaga_vol
/gate/source/MyBeam/useRandomSymmetry   true
/gate/source/MyBeam/ignoreWeight        true