# Gantry
/gate/world/daughters/name                      mylinac
/gate/world/daughters/insert                    box
/gate/mylinac/geometry/setXLength               2.2 m
/gate/mylinac/geometry/setYLength               1.25 m
/gate/mylinac/geometry/setZLength               2.2 m
/gate/mylinac/setMaterial                       Vacuum
/gate/mylinac/placement/setRotationAngle        0. deg
/gate/mylinac/placement/setRotationAxis         0 0 1
/gate/mylinac/placement/setTranslation          0. 1. 0. m
/gate/mylinac/vis/setColor                      red
/gate/mylinac/vis/setVisible                    1

#  Linac Head 
/gate/mylinac/daughters/name                    myLinacHead
/gate/mylinac/daughters/insert                  box
/gate/myLinacHead/geometry/setXLength           1.5 m  
/gate/myLinacHead/geometry/setYLength           1.2 m
/gate/myLinacHead/geometry/setZLength           1.5 m
/gate/myLinacHead/setMaterial                   Vacuum
/gate/myLinacHead/placement/setRotationAxis     0 1 0 
/gate/myLinacHead/placement/setRotationAngle    0.0 deg
/gate/myLinacHead/vis/setColor                  green
/gate/myLinacHead/vis/setVisible                1

# Mylar
# Mylar is described in pdf file as a 0,004 inch  (0,1016 mm) thick foil
# located at 44,3 cm from isocenter 
/gate/myLinacHead/daughters/name                TBmylar
/gate/myLinacHead/daughters/insert              box
/gate/TBmylar/setMaterial                       Mylar
/gate/TBmylar/geometry/setXLength               500.0 mm  
/gate/TBmylar/geometry/setYLength               0.1016 mm  
/gate/TBmylar/geometry/setZLength               500 mm
/gate/TBmylar/placement/setTranslation          0.0 -557.0 0.0 mm
/gate/TBmylar/vis/setColor                      magenta
/gate/TBmylar/vis/forceSolid
/gate/TBmylar/vis/setVisible                    1

# Base Plate
# Base plate is strongly simplified compared to mycarian
# it is only a 0,6 inch thick cylinder with inner radius at  
# Base plate is at 53,3 cm from isocenter and 46,7 cm from source
# 469,7 from fake source
/gate/myLinacHead/daughters/name                TB_BP
/gate/myLinacHead/daughters/insert              cylinder
/gate/TB_BP/geometry/setRmax                    302.26 mm
/gate/TB_BP/geometry/setRmin                    115.57 mm
/gate/TB_BP/geometry/setHeight                  15.24 mm
/gate/TB_BP/placement/setTranslation            0.0 -459.38 0.0 mm
/gate/TB_BP/placement/setRotationAxis           1 0 0
/gate/TB_BP/placement/setRotationAngle          90 deg
/gate/TB_BP/setMaterial                         AcceleratorPrimaryCollimatorMaterial
/gate/TB_BP/vis/setColor                        red
/gate/TB_BP/vis/forceSolid
/gate/TB_BP/vis/setVisible                      1