/gate/myLinacHead/daughters/name        gaga_vol
/gate/myLinacHead/daughters/insert      box
/gate/gaga_vol/geometry/setXLength      0.15 m
/gate/gaga_vol/geometry/setYLength      0.1 um
/gate/gaga_vol/geometry/setZLength      0.15 m
/gate/gaga_vol/setMaterial              Vacuum
/gate/gaga_vol/vis/setColor             blue
/gate/gaga_vol/vis/forceSolid           
/gate/gaga_vol/vis/setVisible           1

/gate/world/daughters/name              inPhantom
/gate/world/daughters/insert            box
/gate/inPhantom/geometry/setXLength     400 mm
/gate/inPhantom/geometry/setYLength     0.1 um
/gate/inPhantom/geometry/setZLength     400 mm
/gate/inPhantom/setMaterial             Vacuum
/gate/inPhantom/vis/setColor            green
/gate/inPhantom/vis/forceSolid 
/gate/inPhantom/vis/setVisible          1
