/gate/world/daughters/name                      outPhSpCylinder
/gate/world/daughters/insert                    cylinder
/gate/outPhSpCylinder/setMaterial               Air
/gate/outPhSpCylinder/geometry/setRmin          369.9  mm
/gate/outPhSpCylinder/geometry/setRmax          370 mm
/gate/outPhSpCylinder/geometry/setHeight        1400 mm
/gate/outPhSpCylinder/vis/setColor              red
/gate/outPhSpCylinder/vis/forceWireframe
#/gate/outPhSpCylinder/vis/forceSolid
/gate/outPhSpCylinder/vis/setVisible            0