/gate/actor/addActor                            DoseActor  depthdose
/gate/actor/depthdose/save                      output/Seg2_Sim/QA_results/gamma-depth.txt
/gate/actor/depthdose/attachTo    	            phantom
/gate/actor/depthdose/stepHitType               random
/gate/actor/depthdose/setPosition               0 0 0 cm
/gate/actor/depthdose/setResolution             1 300 1
/gate/actor/depthdose/setVoxelSize              1 1 1 mm
/gate/actor/depthdose/saveEveryNSeconds         60
/gate/actor/depthdose/enableEdep                true
/gate/actor/depthdose/enableUncertaintyEdep     true
/gate/actor/depthdose/enableDose                false
/gate/actor/depthdose/enableUncertaintyDose     false
/gate/actor/depthdose/enableNumberOfHits        false
