/gate/actor/addActor                                        DoseActor  doseDistribution
/gate/actor/doseDistribution/save                           output/doseDistribution.mhd
/gate/actor/doseDistribution/attachTo                       filmBox
/gate/actor/doseDistribution/stepHitType                    random
/gate/actor/doseDistribution/setResolution                  100 1 100
/gate/actor/doseDistribution/enableDose                     true
/gate/actor/doseDistribution/enableUncertaintyDose          true
#/gate/actor/doseDistribution/enableEdep                    true
#/gate/actor/doseDistribution/enableUncertaintyEdep         true
/gate/actor/doseDistribution/enableDoseToWater              true
/gate/actor/doseDistribution/enableUncertaintyDoseToWater   true
/gate/actor/doseDistribution/saveEveryNSeconds              2000
